---

language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "pypy"
install:
 - pip install coveralls
 - pip install -r requirements_test.txt
script:
  - coverage run manage.py test log
  - coverage report -m
after_success:
  coveralls --verbose
