---

language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "pypy"
install:
 - pip install coveralls
 - pip install -r requirements_test.txt
script:
  - ./manage.py test --with-coverage
after_success:
  coveralls
